### ISSUE TITLE
MySQL gone during install

### ISSUE THREAD

**Issue by dom-breizh** [developeregrem/pve-dockerized#1]
Hi,
While battleing with my non dockerized install, I decided to go the docker way to test anyway. 

Installed clean VM (Ubuntu 20.04 server), docker and all dependendies (for you rinfo a lot of your support documentation is in German which makes it a bit complicated for non german speaker, but thanks to google), It all went well till the last part of the process where username and password are created, the app:first-run process were I got this:

```
 ! [NOTE] Accommodation prepared.                                               

 ! [NOTE] Customers prepared.                                                   

08:48:06 CRITICAL  [console] Error thrown while running command "app:first-run". Message: "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" ["exception" => PDOException { …},"command" => "app:first-run","message" => "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away"]

In Connection.php line 113:
                                                                   
  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away  
                                                                   

app:first-run


   > loading App\DataFixtures\TemplatesFixtures
Do you want to load some initial test data into the application? (yes/no) [no]:yes

   > loading App\DataFixtures\SettingsFixtures
08:48:18 CRITICAL  [console] Error thrown while running command "doctrine:fixtures:load --append --group settings --group customer --group reservation --group invoices". Message: "App\DataFixtures\SettingsFixtures::createRooms(): Argument #3 ($subsidiary) must be of type App\Entity\Subsidiary, null given, called in /var/www/html/fewohbee/src/DataFixtures/SettingsFixtures.php on line 49" ["exception" => TypeError { …},"command" => "doctrine:fixtures:load --append --group settings --group customer --group reservation --group invoices","message" => "App\DataFixtures\SettingsFixtures::createRooms(): Argument #3 ($subsidiary) must be of type App\Entity\Subsidiary, null given, called in /var/www/html/fewohbee/src/DataFixtures/SettingsFixtures.php on line 49"]

In SettingsFixtures.php line 86:
                                                                               
  App\DataFixtures\SettingsFixtures::createRooms(): Argument #3 ($subsidiary)  
   must be of type App\Entity\Subsidiary, null given, called in /var/www/html  
  /fewohbee/src/DataFixtures/SettingsFixtures.php on line 49                   
                                                                               

doctrine:fixtures:load [--append] [--group GROUP] [--em EM] [--purger PURGER] [--purge-exclusions PURGE-EXCLUSIONS] [--shard SHARD] [--purge-with-truncate]

done
```
Looks like the SQL install went wrong somewhere. But since it is within docker, I have no idea how to access it (docker not being my thing... that's why I am still trying the normal install way).

I tried to rerun the install process, but I was told setup was completed...

But although the SQL part is not there, the install finished and you can actually call the application through the browser. Can't connect -> user and password unknown (due to the previous error I guess). So almost there. 

Can you direct me through the correcting steps ? And maybe fix what's wrong in the install process (if it was not my fault).

Thanks

**Comment by developeregrem** [comment]
hi @dom-madrid,
I'm sorry that you are facing some issues in order to use the tool.
And you are right documentation needs to be improved somehow.

Since I've never encountered this issue before we need to make sure that every prerequisite is met.
Have you installed docker for the correct architecture? (arm64, x86, ...)
My documentation here https://github.com/developeregrem/fewohbee/wiki/Docker-Setup is for debian and arm64. According to my documentation please make sure to choose the guide for your architecture and OS. For ubuntu it will be this one here: https://docs.docker.com/engine/install/ubuntu/

If this is correct go to the folder where you cloned the fewohbee files into it and run (reset fewohbee installation):

```
  ./cleanup.sh
  rm .env
```
(maybe with sudo)

and execute the install script again

`sudo ./install.sh`

Afterwards make sure that all containers are running by executing

`docker ps`

... and take a look at the "status" column. Everything needs to be "up".
You can also take a look at the log of a container by executing (e.g. for the db container)

`docker-compose logs db`

If you want to go inside the container you can run

`docker-compose exec db /bin/sh`

BTW: Have you tried my short Howto for non-dockerized installations here: https://github.com/developeregrem/fewohbee/wiki/LAMP-Stack:-Apache,-MySQL,-PHP-(Ubuntu-22) ?

**Comment by developeregrem** [comment]
I assume your problem is solved. Therefore the issue will be closed.
